### ISSUE TITLE
Fails when > appears on a new line

### ISSUE THREAD

**Issue by esperanc** [Rich-Harris/svg-parser#11]
I've noticed that some svgs exported with Adobe Illustrator's SVG plugin fail because several closing angle brackets appear on a separate line. Take a look, for instance, at [this image](https://freesvg.org/woman-on-telephone-vector-illustration). I fixed the image with a regular expression search/replace to move the closing bracket to the end of the preceding line, and everythink worked fine.

**Comment by Rich-Harris** [comment]
Would you consider submitting a PR (with a test)?

**Comment by esperanc** [comment]
Here's an observable notebook showing the problem with an original and a fixed svg:

[SVG Parser Problem Report](https://observablehq.com/d/7a96c1f253e7a8ec)

**Comment by Rich-Harris** [comment]
Yes, but do you think you'd be able to fix it with a pull request? I don't have much of a use for this library any more, so I'm afraid it's unlikely to get fixed otherwise

**Comment by esperanc** [comment]
Hmm. I can try to find the error in the code. I'll see what I can do.

**Comment by TrySound** [comment]
Hi @esperanc I fixed the issue here
https://github.com/Rich-Harris/svg-parser/pull/12

**Comment by esperanc** [comment]
Great!
--Claudio

**Comment by TrySound** [comment]
Published as 2.0.4. Check please

**Comment by Crisfole** [comment]
This parses on a fresh install with the XML from the observable. I'd wager 2 years later this is closable.
