### ISSUE TITLE
svg parser error

### ISSUE THREAD

**Issue by DivXPro** [Rich-Harris/svg-parser#16]
Error: Unexpected end of input (0:0). If this is valid SVG, it's probably a bug in svg-parser. Please raise an issue at https://github.com/Rich-Harris/svg-parser/issues – thanks!

`
<svg xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" width="0" height="0" style="display:none;">
    <symbol viewBox="0 0 24 24" id="ri-24-hours-fill">
        <g>
            <path fill="none" d="M0 0H24V24H0z"/>
            <path d="M12 13c1.657 0 3 1.343 3 3 0 .85-.353 1.616-.92 2.162L12.17 20H15v2H9v-1.724l3.693-3.555c.19-.183.307-.438.307-.721 0-.552-.448-1-1-1s-1 .448-1 1H9c0-1.657 1.343-3 3-3zm6 0v4h2v-4h2v9h-2v-3h-4v-6h2zM4 12c0 2.527 1.171 4.78 3 6.246v2.416C4.011 18.933 2 15.702 2 12h2zm8-10c5.185 0 9.449 3.947 9.95 9h-2.012C19.446 7.054 16.08 4 12 4 9.536 4 7.332 5.114 5.865 6.865L8 9H2V3l2.447 2.446C6.28 3.336 8.984 2 12 2z"/>
        </g>
    </symbol><symbol viewBox="0 0 24 24" id="ri-24-hours-line">
        <g>
            <path fill="none" d="M0 0H24V24H0z"/>
            <path d="M12 13c1.657 0 3 1.343 3 3 0 .85-.353 1.616-.92 2.162L12.17 20H15v2H9v-1.724l3.693-3.555c.19-.183.307-.438.307-.721 0-.552-.448-1-1-1s-1 .448-1 1H9c0-1.657 1.343-3 3-3zm6 0v4h2v-4h2v9h-2v-3h-4v-6h2zM4 12c0 2.527 1.171 4.78 3 6.246v2.416C4.011 18.933 2 15.702 2 12h2zm8-10c5.185 0 9.449 3.947 9.95 9h-2.012C19.446 7.054 16.08 4 12 4 9.25 4 6.824 5.387 5.385 7.5H8v2H2v-6h2V6c1.824-2.43 4.729-4 8-4z"/>
        </g>
    </symbol>
</svg>
`

**Comment by johnculviner** [comment]
I have the same issue as this. the SVG seems valid but it won't load it...

**Comment by TrySound** [comment]
Hi @DivXPro @johnculviner. Make sure you have the latest version in your node_modules. I cannot reproduce the issue with example above.
